FROM node
RUN git clone https://github.com/expressjs/express.git && \
    cd express && \
    npm install express && \ 
    npm install -g express-generator@4 && \
    express /tmp/foo && \
    cd /tmp/foo && \
    npm install
EXPOSE 3000
WORKDIR /tmp/foo
CMD [ "npm", "start" ]






FROM node:19-alpine3.16
RUN apk add npm && apk add git 
RUN git clone https://github.com/expressjs/express.git && \
    cd express && \
    npm install express && \ 
    npm install -g express-generator@4 && \
    express /tmp/foo && \
    cd /tmp/foo && \
    npm install
EXPOSE 3000
WORKDIR /tmp/foo
CMD [ "npm", "start" ]    
