---
version: 0.0.1
services:
  sca_im:
    build: 
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
    - MYSQL_SERVER=172.17.0.2    
    depends_on:
      - sca_db    

  sca_db:
    image: mysql:5.6
    container_name: mysql1
    environment:
      - MYSQL_DATABASE=testsql
      - MYSQL_PASSWORD=rootroot
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_USER=rkdevops
      - MYSQL_SERVER=172.17.0.2