FROM alpine/git AS vcs
RUN cd / && git clone https://github.com/DevProjectsForDevOps/StudentCoursesRestAPI.git

FROM python:3.7-alpine
ARG HOME_DIR='/studentcourses'
COPY --from=vcs /StudentCoursesRestAPI ${HOME_DIR} 
RUN cd ${HOME_DIR}
EXPOSE 8080
WORKDIR ${HOME_DIR}
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "app.py"]