### Creating jenkins Image From Docker File.

FROM ubuntu:22.04
RUN apt update
RUN apt install -y openjdk-17-jdk
LABEL Author="Ravikiran" organisation="Qualitythought"
RUN apt install -y curl
RUN curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
RUN echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian binary/ | tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null 
RUN apt-get update
RUN apt-get install -y jenkins
USER jenkins
EXPOSE 8080 
CMD [ "/usr/bin/jenkins" ]



