
#multistaged build

FROM alpine/git AS VCS
RUN cd / && git clone https://github.com/spring-projects/spring-petclinic.git 

FROM maven:3-amazoncorretto-17 AS builder
COPY --from=VCS /spring-petclinic /spring-petclinic
RUN cd /spring-petclinic && mvn package


FROM amazoncorretto:17-alpine3.17-jdk AS executor
EXPOSE 8080
ARG HOME_DIR=/spc
WORKDIR ${HOME_DIR}
COPY --from=builder /spring-petclinic/target/spring-petclinic-3.0.0-SNAPSHOT.jar ${HOME_DIR}/spring-petclinic.jar
EXPOSE 8080
CMD ["java","-jar","spring-petclinic.jar"]


